// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { TransferHelper$Type } from "./TransferHelper";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TransferHelper"]: TransferHelper$Type;
    ["contracts/help/TransferHelper.sol:TransferHelper"]: TransferHelper$Type;
  }
}
