// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface TransferHelper$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "TransferHelper",
  "sourceName": "contracts/help/TransferHelper.sol",
  "abi": [],
  "bytecode": "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220d0f7c78e2d6e6f47dd90183949816639e03c5fa1c8e983dc4bb0390ec414b0ca64736f6c63430008180033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220d0f7c78e2d6e6f47dd90183949816639e03c5fa1c8e983dc4bb0390ec414b0ca64736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "TransferHelper",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<TransferHelper$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/help/TransferHelper.sol:TransferHelper",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<TransferHelper$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "TransferHelper",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<TransferHelper$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/help/TransferHelper.sol:TransferHelper",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<TransferHelper$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "TransferHelper",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<TransferHelper$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/help/TransferHelper.sol:TransferHelper",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<TransferHelper$Type["abi"]>>;
}
