// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { MonoTrade$Type } from "./MonoTrade";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MonoTrade"]: MonoTrade$Type;
    ["contracts/v2/MonoTrade.sol:MonoTrade"]: MonoTrade$Type;
  }
}
