// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IFactory$Type } from "./IFactory";
import { MonoTrade$Type } from "./MonoTrade";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IFactory"]: IFactory$Type;
    ["MonoTrade"]: MonoTrade$Type;
    ["contracts/v2/MonoTrade.sol:IFactory"]: IFactory$Type;
    ["contracts/v2/MonoTrade.sol:MonoTrade"]: MonoTrade$Type;
  }
}
