// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Mars$Type } from "./Mars";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Mars"]: Mars$Type;
    ["contracts/v2/Mars.sol:Mars"]: Mars$Type;
  }
}
