// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { MarsHelp$Type } from "./MarsHelp";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MarsHelp"]: MarsHelp$Type;
    ["contracts/MarsHelp.sol:MarsHelp"]: MarsHelp$Type;
  }
}
