// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IUniswapV3PoolEvents$Type } from "./IUniswapV3PoolEvents";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IUniswapV3PoolEvents"]: IUniswapV3PoolEvents$Type;
    ["@uniswap/v3-core/contracts/interfaces/pool/IUniswapV3PoolEvents.sol:IUniswapV3PoolEvents"]: IUniswapV3PoolEvents$Type;
  }
}
