// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { PairFactory$Type } from "./PairFactory";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["PairFactory"]: PairFactory$Type;
    ["contracts/PairFactory.sol:PairFactory"]: PairFactory$Type;
  }
}
