// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IPeripheryImmutableState$Type } from "./IPeripheryImmutableState";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IPeripheryImmutableState"]: IPeripheryImmutableState$Type;
    ["@uniswap/v3-periphery/contracts/interfaces/IPeripheryImmutableState.sol:IPeripheryImmutableState"]: IPeripheryImmutableState$Type;
  }
}
