// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IPeripheryImmutableState$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IPeripheryImmutableState",
  "sourceName": "@uniswap/v3-periphery/contracts/interfaces/IPeripheryImmutableState.sol",
  "abi": [
    {
      "inputs": [],
      "name": "WETH9",
      "outputs": [
        {
          "internalType": "address",
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "factory",
      "outputs": [
        {
          "internalType": "address",
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IPeripheryImmutableState",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IPeripheryImmutableState$Type["abi"]>>;
  export function deployContract(
    contractName: "@uniswap/v3-periphery/contracts/interfaces/IPeripheryImmutableState.sol:IPeripheryImmutableState",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IPeripheryImmutableState$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IPeripheryImmutableState",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IPeripheryImmutableState$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@uniswap/v3-periphery/contracts/interfaces/IPeripheryImmutableState.sol:IPeripheryImmutableState",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IPeripheryImmutableState$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IPeripheryImmutableState",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IPeripheryImmutableState$Type["abi"]>>;
  export function getContractAt(
    contractName: "@uniswap/v3-periphery/contracts/interfaces/IPeripheryImmutableState.sol:IPeripheryImmutableState",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IPeripheryImmutableState$Type["abi"]>>;
}
