// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IUniswapV3PoolDerivedState$Type } from "./IUniswapV3PoolDerivedState";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IUniswapV3PoolDerivedState"]: IUniswapV3PoolDerivedState$Type;
    ["@uniswap/v3-core/contracts/interfaces/pool/IUniswapV3PoolDerivedState.sol:IUniswapV3PoolDerivedState"]: IUniswapV3PoolDerivedState$Type;
  }
}
