// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { MarsFactory$Type } from "./MarsFactory";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MarsFactory"]: MarsFactory$Type;
    ["contracts/MarsFactory.sol:MarsFactory"]: MarsFactory$Type;
  }
}
