// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IERC20$Type } from "./IERC20";
import { IFactory$Type } from "./IFactory";
import { MonoTradeV2$Type } from "./MonoTradeV2";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IERC20"]: IERC20$Type;
    ["IFactory"]: IFactory$Type;
    ["MonoTradeV2"]: MonoTradeV2$Type;
    ["contracts/v2/MonoTradeV2.sol:IERC20"]: IERC20$Type;
    ["contracts/v2/MonoTradeV2.sol:IFactory"]: IFactory$Type;
    ["contracts/v2/MonoTradeV2.sol:MonoTradeV2"]: MonoTradeV2$Type;
  }
}
