// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IERC20$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IERC20",
  "sourceName": "contracts/v2/MonoTradeV2.sol",
  "abi": [
    {
      "inputs": [],
      "name": "decimals",
      "outputs": [
        {
          "internalType": "uint8",
          "name": "",
          "type": "uint8"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "contracts/v2/MonoTradeV2.sol:IERC20",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IERC20$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "contracts/v2/MonoTradeV2.sol:IERC20",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IERC20$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "contracts/v2/MonoTradeV2.sol:IERC20",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IERC20$Type["abi"]>>;
}
