// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IUniswapV3PoolImmutables$Type } from "./IUniswapV3PoolImmutables";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IUniswapV3PoolImmutables"]: IUniswapV3PoolImmutables$Type;
    ["@uniswap/v3-core/contracts/interfaces/pool/IUniswapV3PoolImmutables.sol:IUniswapV3PoolImmutables"]: IUniswapV3PoolImmutables$Type;
  }
}
