// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { PoolAddress$Type } from "./PoolAddress";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["PoolAddress"]: PoolAddress$Type;
    ["@uniswap/v3-periphery/contracts/libraries/PoolAddress.sol:PoolAddress"]: PoolAddress$Type;
  }
}
