// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface PoolAddress$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "PoolAddress",
  "sourceName": "@uniswap/v3-periphery/contracts/libraries/PoolAddress.sol",
  "abi": [],
  "bytecode": "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212208ee46ea59a6815549955d93cbe9c993bda9add61d910fa87f91f3ef14f3b3e9764736f6c63430008180033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212208ee46ea59a6815549955d93cbe9c993bda9add61d910fa87f91f3ef14f3b3e9764736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "PoolAddress",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<PoolAddress$Type["abi"]>>;
  export function deployContract(
    contractName: "@uniswap/v3-periphery/contracts/libraries/PoolAddress.sol:PoolAddress",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<PoolAddress$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "PoolAddress",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<PoolAddress$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@uniswap/v3-periphery/contracts/libraries/PoolAddress.sol:PoolAddress",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<PoolAddress$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "PoolAddress",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<PoolAddress$Type["abi"]>>;
  export function getContractAt(
    contractName: "@uniswap/v3-periphery/contracts/libraries/PoolAddress.sol:PoolAddress",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<PoolAddress$Type["abi"]>>;
}
