// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Multicall$Type } from "./Multicall";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Multicall"]: Multicall$Type;
    ["contracts/help/Multicall.sol:Multicall"]: Multicall$Type;
  }
}
