// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IUniswapV3PoolState$Type } from "./IUniswapV3PoolState";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IUniswapV3PoolState"]: IUniswapV3PoolState$Type;
    ["@uniswap/v3-core/contracts/interfaces/pool/IUniswapV3PoolState.sol:IUniswapV3PoolState"]: IUniswapV3PoolState$Type;
  }
}
