// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { OrderPool$Type } from "./OrderPool";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["OrderPool"]: OrderPool$Type;
    ["contracts/OrderPool.sol:OrderPool"]: OrderPool$Type;
  }
}
