// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { PairReadHelp$Type } from "./PairReadHelp";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["PairReadHelp"]: PairReadHelp$Type;
    ["contracts/PairReadHelp.sol:PairReadHelp"]: PairReadHelp$Type;
  }
}
