// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IUniswapV3Pool$Type } from "./IUniswapV3Pool";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IUniswapV3Pool"]: IUniswapV3Pool$Type;
    ["@uniswap/v3-core/contracts/interfaces/IUniswapV3Pool.sol:IUniswapV3Pool"]: IUniswapV3Pool$Type;
  }
}
