// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IUniswapV3PoolOwnerActions$Type } from "./IUniswapV3PoolOwnerActions";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IUniswapV3PoolOwnerActions"]: IUniswapV3PoolOwnerActions$Type;
    ["@uniswap/v3-core/contracts/interfaces/pool/IUniswapV3PoolOwnerActions.sol:IUniswapV3PoolOwnerActions"]: IUniswapV3PoolOwnerActions$Type;
  }
}
