// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { TickMath$Type } from "./TickMath";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TickMath"]: TickMath$Type;
    ["@uniswap/v3-core/contracts/libraries/TickMath.sol:TickMath"]: TickMath$Type;
  }
}
