// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Pair$Type } from "./Pair";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Pair"]: Pair$Type;
    ["contracts/Pair.sol:Pair"]: Pair$Type;
  }
}
