// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { PeripheryImmutableState$Type } from "./PeripheryImmutableState";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["PeripheryImmutableState"]: PeripheryImmutableState$Type;
    ["@uniswap/v3-periphery/contracts/base/PeripheryImmutableState.sol:PeripheryImmutableState"]: PeripheryImmutableState$Type;
  }
}
