// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Path$Type } from "./Path";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Path"]: Path$Type;
    ["@uniswap/v3-periphery/contracts/libraries/Path.sol:Path"]: Path$Type;
  }
}
