// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Path$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Path",
  "sourceName": "@uniswap/v3-periphery/contracts/libraries/Path.sol",
  "abi": [],
  "bytecode": "0x60566023600b82828239805160001a607314601657fe5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212209e1bcacc61b1c416c10fd94a993a75e7b31e5655cdeabbbf612a8fd4921fdb7564736f6c63430007060033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212209e1bcacc61b1c416c10fd94a993a75e7b31e5655cdeabbbf612a8fd4921fdb7564736f6c63430007060033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Path",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Path$Type["abi"]>>;
  export function deployContract(
    contractName: "@uniswap/v3-periphery/contracts/libraries/Path.sol:Path",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Path$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Path",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Path$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@uniswap/v3-periphery/contracts/libraries/Path.sol:Path",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Path$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Path",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Path$Type["abi"]>>;
  export function getContractAt(
    contractName: "@uniswap/v3-periphery/contracts/libraries/Path.sol:Path",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Path$Type["abi"]>>;
}
