// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { TradeService$Type } from "./TradeService";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TradeService"]: TradeService$Type;
    ["contracts/v2/TradeService.sol:TradeService"]: TradeService$Type;
  }
}
