// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { MockZKID$Type } from "./MockZKID";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MockZKID"]: MockZKID$Type;
    ["contracts/mock/MockZKID.sol:MockZKID"]: MockZKID$Type;
  }
}
