// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { MarsPair$Type } from "./MarsPair";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MarsPair"]: MarsPair$Type;
    ["contracts/MarsPair.sol:MarsPair"]: MarsPair$Type;
  }
}
