// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { MarsToken$Type } from "./MarsToken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MarsToken"]: MarsToken$Type;
    ["contracts/MarsToken.sol:MarsToken"]: MarsToken$Type;
  }
}
