// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Mining$Type } from "./Mining";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Mining"]: Mining$Type;
    ["contracts/v2/Mining.sol:Mining"]: Mining$Type;
  }
}
