// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IUniswapV3PoolActions$Type } from "./IUniswapV3PoolActions";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IUniswapV3PoolActions"]: IUniswapV3PoolActions$Type;
    ["@uniswap/v3-core/contracts/interfaces/pool/IUniswapV3PoolActions.sol:IUniswapV3PoolActions"]: IUniswapV3PoolActions$Type;
  }
}
