// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { MockERC721$Type } from "./MockERC721";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MockERC721"]: MockERC721$Type;
    ["contracts/mock/MockERC721.sol:MockERC721"]: MockERC721$Type;
  }
}
