// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface SafeCast$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "SafeCast",
  "sourceName": "@uniswap/v3-core/contracts/libraries/SafeCast.sol",
  "abi": [],
  "bytecode": "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122094aa07c37b5cf54cc385af8228d82e3697f384dfdcc2a67277b1f0ef18b7391164736f6c63430008180033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122094aa07c37b5cf54cc385af8228d82e3697f384dfdcc2a67277b1f0ef18b7391164736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "SafeCast",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SafeCast$Type["abi"]>>;
  export function deployContract(
    contractName: "@uniswap/v3-core/contracts/libraries/SafeCast.sol:SafeCast",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SafeCast$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "SafeCast",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SafeCast$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@uniswap/v3-core/contracts/libraries/SafeCast.sol:SafeCast",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SafeCast$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "SafeCast",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SafeCast$Type["abi"]>>;
  export function getContractAt(
    contractName: "@uniswap/v3-core/contracts/libraries/SafeCast.sol:SafeCast",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SafeCast$Type["abi"]>>;
}
