// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { MarsMining$Type } from "./MarsMining";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MarsMining"]: MarsMining$Type;
    ["contracts/MarsMining.sol:MarsMining"]: MarsMining$Type;
  }
}
