// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IUniswapV3Factory$Type } from "./IUniswapV3Factory";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IUniswapV3Factory"]: IUniswapV3Factory$Type;
    ["@uniswap/v3-core/contracts/interfaces/IUniswapV3Factory.sol:IUniswapV3Factory"]: IUniswapV3Factory$Type;
  }
}
