// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IQuoter$Type } from "./IQuoter";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IQuoter"]: IQuoter$Type;
    ["@uniswap/v3-periphery/contracts/interfaces/IQuoter.sol:IQuoter"]: IQuoter$Type;
  }
}
