// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { CallbackValidation$Type } from "./CallbackValidation";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["CallbackValidation"]: CallbackValidation$Type;
    ["@uniswap/v3-periphery/contracts/libraries/CallbackValidation.sol:CallbackValidation"]: CallbackValidation$Type;
  }
}
