// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface CallbackValidation$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "CallbackValidation",
  "sourceName": "@uniswap/v3-periphery/contracts/libraries/CallbackValidation.sol",
  "abi": [],
  "bytecode": "0x60566023600b82828239805160001a607314601657fe5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122032ab0e4c0c63b2990f98768db94e9c381d3b751f2ae6829a6cc107240fcb30ce64736f6c63430007060033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122032ab0e4c0c63b2990f98768db94e9c381d3b751f2ae6829a6cc107240fcb30ce64736f6c63430007060033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "CallbackValidation",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<CallbackValidation$Type["abi"]>>;
  export function deployContract(
    contractName: "@uniswap/v3-periphery/contracts/libraries/CallbackValidation.sol:CallbackValidation",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<CallbackValidation$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "CallbackValidation",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<CallbackValidation$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@uniswap/v3-periphery/contracts/libraries/CallbackValidation.sol:CallbackValidation",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<CallbackValidation$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "CallbackValidation",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<CallbackValidation$Type["abi"]>>;
  export function getContractAt(
    contractName: "@uniswap/v3-periphery/contracts/libraries/CallbackValidation.sol:CallbackValidation",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<CallbackValidation$Type["abi"]>>;
}
