// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { QuoterV3$Type } from "./QuoterV3";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["QuoterV3"]: QuoterV3$Type;
    ["contracts/help/QuoterV3.sol:QuoterV3"]: QuoterV3$Type;
  }
}
