// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Multicall3$Type } from "./Multicall3";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Multicall3"]: Multicall3$Type;
    ["contracts/help/Multicall3.sol:Multicall3"]: Multicall3$Type;
  }
}
