// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IUniswapV3SwapCallback$Type } from "./IUniswapV3SwapCallback";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IUniswapV3SwapCallback"]: IUniswapV3SwapCallback$Type;
    ["@uniswap/v3-core/contracts/interfaces/callback/IUniswapV3SwapCallback.sol:IUniswapV3SwapCallback"]: IUniswapV3SwapCallback$Type;
  }
}
