// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { BytesLib$Type } from "./BytesLib";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BytesLib"]: BytesLib$Type;
    ["@uniswap/v3-periphery/contracts/libraries/BytesLib.sol:BytesLib"]: BytesLib$Type;
  }
}
