// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface BytesLib$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "BytesLib",
  "sourceName": "@uniswap/v3-periphery/contracts/libraries/BytesLib.sol",
  "abi": [],
  "bytecode": "0x60566023600b82828239805160001a607314601657fe5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220939b554eeb952023ad6b7ff6b0d2d0cd8f33fafcf47d19abda64dd15450e3ed664736f6c63430007060033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220939b554eeb952023ad6b7ff6b0d2d0cd8f33fafcf47d19abda64dd15450e3ed664736f6c63430007060033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "BytesLib",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<BytesLib$Type["abi"]>>;
  export function deployContract(
    contractName: "@uniswap/v3-periphery/contracts/libraries/BytesLib.sol:BytesLib",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<BytesLib$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "BytesLib",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<BytesLib$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@uniswap/v3-periphery/contracts/libraries/BytesLib.sol:BytesLib",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<BytesLib$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "BytesLib",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<BytesLib$Type["abi"]>>;
  export function getContractAt(
    contractName: "@uniswap/v3-periphery/contracts/libraries/BytesLib.sol:BytesLib",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<BytesLib$Type["abi"]>>;
}
