// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { MarsService$Type } from "./MarsService";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MarsService"]: MarsService$Type;
    ["contracts/MarsService.sol:MarsService"]: MarsService$Type;
  }
}
