// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { TokenNFTBridge$Type } from "./TokenNFTBridge";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TokenNFTBridge"]: TokenNFTBridge$Type;
    ["contracts/token-nft/TokenNFTBridge.sol:TokenNFTBridge"]: TokenNFTBridge$Type;
  }
}
